plugins/org.jboss.tools.ws.creation.core/src/org/jboss/tools/ws/creation/core/commands/AbstractGenerateCodeCommand.java
=> JBIDE-13414 - Issue with client generation error slipping through the

tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/internal/metamodel/builder/JavaElementDeltaScannerTestCase.java, tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/internal/metamodel/builder/ResourceChangedProcessingTestCase.java, tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/junitrules/ResourcesUtils.java, tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/junitrules/TestProjectMonitor.java, tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/junitrules/TestProjectSynchronizator.java, tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/junitrules/WorkbenchTasks.java
Allow for multiple (5) attempts to delete a resource
before failing
=> JBIDE-20608 - Build failures on Jenkins/Other OS

tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/internal/metamodel/builder/JavaElement11ChangedProcessingTestCase.java, tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/junitrules/ResourcesUtils.java, tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/junitrules/WorkbenchTasks.java, tests/org.jboss.tools.ws.jaxrs.ui.test/src/org/jboss/tools/ws/jaxrs/ui/cnf/UriMappingsContentProviderTestCase.java, tests/org.jboss.tools.ws.jaxrs.ui.test/src/org/jboss/tools/ws/jaxrs/ui/internal/validation/JaxrsApplicationValidatorTestCase.java, tests/org.jboss.tools.ws.jaxrs.ui.test/src/org/jboss/tools/ws/jaxrs/ui/internal/validation/JaxrsHttpMethodValidatorTestCase.java, tests/org.jboss.tools.ws.jaxrs.ui.test/src/org/jboss/tools/ws/jaxrs/ui/wizards/JaxrsApplicationCreationWizardPageTestCase.java
Added missing case of resource deletion
Wait for resource content change before continuing test
=> JBIDE-20608 - Build failure on Jenkins/OtherOS

plugins/org.jboss.tools.ws.jaxrs.core/src/org/jboss/tools/ws/jaxrs/core/internal/metamodel/domain/JaxrsProvider.java, plugins/org.jboss.tools.ws.jaxrs.core/src/org/jboss/tools/ws/jaxrs/core/metamodel/domain/EnumElementKind.java, plugins/org.jboss.tools.ws.jaxrs.core/src/org/jboss/tools/ws/jaxrs/core/utils/JaxrsClassnames.java, tests/org.jboss.tools.ws.jaxrs.core.test/resources/CustomDynamicFeature.txt, tests/org.jboss.tools.ws.jaxrs.ui.test/src/org/jboss/tools/ws/jaxrs/ui/internal/validation/Jaxrs20ResourceValidatorTestCase.java
Added support for classes that implement the 'javax.ws.rs.container.DynamicFeature'
interface.
=> JBIDE-21977 - Unexpected JAX-RS validation error for client filters

pom.xml
=> [JBIDE-23199] - For JBIDE 4.4.2.AM1: Prepare for 4.4.2.AM1 / 10.2.0.AM1 [Webservices]

plugins/org.jboss.tools.ws.jaxrs.core/src/org/jboss/tools/ws/jaxrs/core/internal/metamodel/domain/JaxrsMetamodel.java, plugins/org.jboss.tools.ws.jaxrs.core/src/org/jboss/tools/ws/jaxrs/core/jdt/JdtUtils.java, tests/org.jboss.tools.ws.jaxrs.core.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/jdt/JdtUtilsTestCase.java
Checking if the member still exists
Signed-off-by: Xavier Coulon <xcoulon@redhat.com>
=> JBIDE-22896 - JavaModelException below JdtUtils.findDeclaringNode

plugins/org.jboss.tools.ws.jaxrs.ui/src/org/jboss/tools/ws/jaxrs/ui/preferences/JaxrsSettingsPreferencePage.java
=> [JBIDE-23055] - Repeated toggling of JAX-RS support on project does not cause it to rebuild

test-framework/org.jboss.tools.ws.reddeer/src/org/jboss/tools/ws/reddeer/jaxrs/core/RESTfulWebService.java, test-framework/org.jboss.tools.ws.reddeer/src/org/jboss/tools/ws/reddeer/jaxrs/core/RESTfulWebServicesNode.java
Signed-off-by: Pavol Srna <psrna@redhat.com>
=> JBIDE-25141 Fix class cast exception in ws.reddeer

test-framework/org.jboss.tools.ws.reddeer/src/org/jboss/tools/ws/reddeer/ui/wizards/jst/servlet/DynamicWebProjectWizard.java
Signed-off-by: Pavol Srna <psrna@redhat.com>
=> JBIDE-25147 Fix missing shell text in ws.reddeer DynamicWebProjectWizard constructor

plugins/org.jboss.tools.ws.jaxrs.ui/src/org/jboss/tools/ws/jaxrs/ui/internal/validation/AbstractJaxrsElementValidatorDelegate.java
=> [JBIDE-26040] - Error for JAX-RS 2.1 @Context types

plugins/org.jboss.tools.ws.jaxws.ui/META-INF/MANIFEST.MF
=> JBIDE-26505 - webservices compilation errors on Java11+

tests/org.jboss.tools.ws.jaxws.core.test/META-INF/MANIFEST.MF
=> JBIDE-26505 - webservices test errors on Java11+

plugins/org.jboss.tools.ws.jaxrs.core/src/org/jboss/tools/ws/jaxrs/core/internal/metamodel/domain/JaxrsProvider.java, plugins/org.jboss.tools.ws.jaxrs.core/src/org/jboss/tools/ws/jaxrs/core/metamodel/domain/EnumElementKind.java, plugins/org.jboss.tools.ws.jaxrs.core/src/org/jboss/tools/ws/jaxrs/core/utils/JaxrsClassnames.java, tests/org.jboss.tools.ws.jaxrs.core.test/projects/org.jboss.tools.ws.jaxrs.tests.sampleproject2/src/main/java/org/jboss/tools/ws/jaxrs/sample/services/CarDynamicFeature.java, tests/org.jboss.tools.ws.jaxrs.core.test/projects/org.jboss.tools.ws.jaxrs.tests.sampleproject2/src/main/java/org/jboss/tools/ws/jaxrs/sample/services/CarFeature.java, tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/internal/metamodel/domain/Jaxrs20MetamodelTestCase.java, tests/org.jboss.tools.ws.jaxrs.ui.test/src/org/jboss/tools/ws/jaxrs/ui/internal/validation/Jaxrs20ProviderValidatorTestCase.java
=> JBIDE-25669: Unexpected JAX-RS validation error for Feature

test-framework/org.jboss.tools.ws.reddeer/META-INF/MANIFEST.MF, test-framework/org.jboss.tools.ws.reddeer/src/org/jboss/tools/ws/reddeer/ui/tester/views/WsTesterView.java
- fixes JBIDE-27021
Signed-off-by: Ondrej Dockal <odockal@redhat.com>
=> Fixing itests, refactoring

.github/workflows/pr-check.yml
Signed-off-by: Ondrej Dockal <odockal@redhat.com>
=> Draft: Introduce Github Actions workflow for pr check

.github/workflows/build_test.yml, .github/workflows/publish_reports.yml
Also add publishing of test results in publish_results.yml workflow
=> Introduce Build and Test workflow as JBT Webservices PR Check

.github/workflows/publish_reports.yml
Signed-off-by: Ondrej Dockal <odockal@redhat.com>
=> Update publishing pattern

plugins/org.jboss.tools.ws.jaxrs.ui/src/org/jboss/tools/ws/jaxrs/ui/wizards/JaxrsElementCreationUtils.java
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>
=> JBIDE-27730: fix NPE when creating JAX-RS application

plugins/org.jboss.tools.ws.jaxrs.ui/src/org/jboss/tools/ws/jaxrs/ui/wizards/JaxrsElementCreationUtils.java
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>
=> JBIDE-27730 : fix NPE

tests/org.jboss.tools.ws.jaxrs.core.test/build.properties, tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/internal/metamodel/builder/JavaElement11ChangedProcessingTestCase.java, tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/internal/metamodel/builder/JaxrsMetamodelBuilderTestCase.java, tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/junitrules/JaxrsMetamodelMonitor.java, tests/org.jboss.tools.ws.jaxrs.core.test/src/org/jboss/tools/ws/jaxrs/core/junitrules/TestProjectMonitor.java, tests/org.jboss.tools.ws.jaxrs.ui.test/src/org/jboss/tools/ws/jaxrs/ui/wizards/JaxrsApplicationCreationWizardPageTestCase.java, tests/org.jboss.tools.ws.jaxrs.ui.test/src/org/jboss/tools/ws/jaxrs/ui/wizards/JaxrsResourceCreationWizardPageTestCase.java
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>
=> JBIDE-27721: fix timeout
